#!/usr/bin/env python3
import RPi.GPIO as GPIO
import random as r
import time

pins = [21,20,12,16]
p = [p1,p2,p3,p4]


GPIO.setmode(GPIO.BCM)
GPIO.setup(pins, GPIO.OUT)
for c_p in p:
    c_p.PWM(pins[p.index(c_P)], 50)
    c_p.start(7.5)
try:
    while True:
        main_boom = [r.uniform(2.5,12.5),r.randint(0,1)]
        roataor = [r.uniform(2.5,12.5),r.randint(0,1)]
        lower_servo = [r.uniform(2.5,12.5),r.randint(0,1)]
        upper_boom = [r.uniform(2.5,12.5),r.randint(0,1)]
        servos = [main_boom, roator, lower_servo, upper_boom]
        for servo in servos:
            if servo[1] == 1:
                servo.ChangeDutyCycle(servo[0])
except KeyboardInterrupt:
    GPIO.cleanup()
    exit()


