#!/usr/bin/env python3
import curses as c
import time
stdscr = c.initscr()
stdscr.keypad(True)
c.noecho()
c.cbreak()
size = stdscr.getmaxyx()
y = round(size[0]/2)
x = round(size[1]/2-3)
stdscr.addstr(y,x,'Robot!')

def check(what):
    global y
    global x
    if what == 'up':
        y -= 1
        if y < 0:
            y += 1
            return False
        else:
            return True
    elif what == 'down':
        y += 1
        if y > size[0]:
            y -= 1
            return False
        else:
            return True
    elif what == 'right':
        x += 1
        if x > size[1]:
            x -= 1
            return False
        else:
            return True
    elif what == 'left':
        x -= 1
        if x < 0:
            x += 1
            return False
        else:
            return True
    else:
        return False
def fire(direc):
    xf = x
    yf = y
    if direc == 'up':
        while yf > 0:
            stdscr.clear()
            stdscr.addstr(yf,xf,"|")
            stdscr.addstr(y,x,'Robot!')
            yf -= 1
            stdscr.refresh()
            time.sleep(0.1)
    if direc == 'down':
        while yf < size[0]:
            stdscr.clear()
            stdscr.addstr(yf,xf,"|")
            stdscr.addstr(y,x,'Robot!')
            yf += 1
            stdscr.refresh()
            time.sleep(0.1)
    if direc == 'right':
        while xf < size[1]:
            stdscr.clear()
            stdscr.addstr(yf,xf,"-")
            stdscr.addstr(y,x,'Robot!')
            xf += 1
            stdscr.refresh()
            time.sleep(0.1)
    if direc == 'left':
        while xf > 0:
            stdscr.clear()
            stdscr.addstr(yf,xf,"-")
            stdscr.addstr(y,x,'Robot!')
            xf -= 1
            stdscr.refresh()
            time.sleep(0.1)
        
try:
    while True:
        key = stdscr.getch()
        if key == ord('w'):
            if check('up'):
                stdscr.clear()
                stdscr.addstr(y,x,'Robot!')
        elif key == ord('s'):
            if check('down'):
                stdscr.clear()
                stdscr.addstr(y,x,'Robot!')
        elif key == ord('d'):
            if check('right'):
                stdscr.clear()
                stdscr.addstr(y,x,'Robot!')
        elif key == ord('a'):
            if check('left'):
                stdscr.clear()
                stdscr.addstr(y,x,'Robot!')
        elif key == c.KEY_UP:
            fire('up')
        elif key == c.KEY_DOWN:
            fire('down')
        elif key == c.KEY_RIGHT:
            fire('right')
        elif key == c.KEY_LEFT:
            fire('left')
except KeyboardInterrupt:
    c.endwin()
    exit()   
