#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time
pins = [12,16,21,20,26,5]
GPIO.setmode(GPIO.BCM)
GPIO.setup(pins, GPIO.OUT)
GPIO.setup(19, GPIO.IN)

p = GPIO.PWM(12, 50)
p2 = GPIO.PWM(16, 50)
p3 = GPIO.PWM(21, 50)
p4 = GPIO.PWM(20, 50)

time.sleep(1)

p.start(7.5)
p2.start(7.5)
p3.start(7.5)
p4.start(7.5)

time.sleep(1)

def check_dis():
    GPIO.output(26, 1)
    time.sleep(0.00001)
    GPIO.output(26, 0)

    while GPIO.input(19) == 0:
        start = time.time()
    while GPIO.input(19) == 1:
        stop = time.time()

    duration = stop - start

    distance = duration * 17150

    return round(distance, 2)

mode = 0
move = 7.5
while True:
    current_dis = check_dis()
    if current_dis <= 35:
        GPIO.output(5, 1)
        pass
    elif current_dis > 3000:
        pass
    else:
        GPIO.output(5, 0)
        if move >= 12.5:
            mode = 1
        elif move <= 2.5:
            mode = 0

        if mode == 0:
            move += 0.1
        elif mode == 1:
            move -= 0.1
    move = round(move, 1)
    p.ChangeDutyCycle(7.5)
    p2.ChangeDutyCycle(7.5)
    p3.ChangeDutyCycle(7.5)
    p4.ChangeDutyCycle(move)
    time.sleep(0.1)

