#!/usr/bin/env python3
import evdev

#devices = [evdev.InputDevice(fn) for fn in evdev.list_devices()]
#for device in devices:
#    print(device.fn, device.name, device.phys)
device = evdev.InputDevice('/dev/input/event0')
print(device)

for event in device.read_loop():
    print(str(event))
