#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

pins = [16,12,21]

GPIO.setup(pins, GPIO.OUT)

p = GPIO.PWM(16, 50)
p2 = GPIO.PWM(12, 50)
p3 = GPIO.PWM(21, 50)

while True:
    p.ChangeDutyCycle(2.5)
    p2.ChangeDutyCycle(2.5)
    p3.ChangeDutyCycle(2.5)
    time.sleep(1)
    p.ChangeDutyCycle(7.5)
    p2.ChangeDutyCycle(7.5)
    p3.ChangeDutyCycle(7.5)
    time.sleep(1)
    p.ChangeDutyCycle(12.5)
    p2.ChangeDutyCycle(12.5)
    p3.ChangeDutyCycle(12.5)
    time.sleep(1)


