#!/usr/bin/env python3
import curses
from curses.textpad import Textbox, rectangle
s = curses.initscr()

editwin = curses.newwin(5,30,2,1)
rectangle(s,1,0,1+5+1,1+30+1)
s.refresh()
box = Textbox(editwin)
box.edit()
message = box.gather()
curses.endwin()
print(message)


