#!/usr/bin/env python3
import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)
GPIO.setup(12, GPIO.OUT)
p = GPIO.PWM(12, 50)
p.start(15.5)
try:
    while True:
        p.ChangeDutyCycle(20.5)
        time.sleep(1.5)
        #time.sleep(2) 
        #p.ChangeDutyCycle(.5)
        #time.sleep(2)
        #p.ChangeDutyCycle(.5)
        #time.sleep(2)
except KeyboardInterrupt:
    GPIO.cleanup()
    exit()
